services:
  hrms-backend:
    build:
      context: https://github.com/7UpadhyayKrishna/hrms-backend.git
      dockerfile: Dockerfile
    container_name: hrms-backend
    restart: always
    env_file:
      - ./hrms-backend/.env
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=http://localhost:5173,http://localhost,http://localhost:80
    expose:
      - "5001"
    networks:
      - hrms-network

  hrms-spc:
    build:
      context: https://github.com/7UpadhyayKrishna/hrms-spc.git#hrms-spc
      dockerfile: hrms-spc/Dockerfile
    container_name: hrms-spc
    restart: always
    ports:
      - "80:80"
    networks:
      - hrms-network

networks:
  hrms-network:
    driver: bridge